# This is a basic workflow to help you get started with Actions

name: 连接测试

# Controls when the workflow will run
on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: 迁出代码
      uses: actions/checkout@v2
    - name: 设置时区
      run: sudo timedatectl set-timezone 'Asia/Shanghai'
    - name: CLASH环境部署
      run: |
        ulimit -SHn 65536
        GO_TAR=go.tar.gz
        GO=`pwd`/go/bin/go
        curl -L -s https://golang.org/dl/go1.16.6.linux-amd64.tar.gz -o ${GO_TAR}
        tar -xvf ${GO_TAR} >/dev/null
        ${GO} install github.com/Dreamacro/clash@latest
    - name: 连接测试
      run: |
        A=VmessActions/subscribe/latest_pool.yaml
        B=VmessActions/subscribe/valid_pool.yaml
        bash ./VmessActions/connection_test.sh "${A}" "${B}"
