name: 自动采集
on:
  workflow_dispatch:
  schedule:
  #  - cron: '10 */2 * * *'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: 迁出代码
      uses: actions/checkout@v2
    - name: 设置时区
      run: sudo timedatectl set-timezone 'Asia/Shanghai'
    - name: 系统设置
      run: |
        ulimit -SHn 65536
        GITHUB='https/github.com'
        OS='linux-amd64'
        USER='Dreamacro'
        APP='clash'
        REPO=$USER/$APP
        FILE=$APP.gz
        PROXY_URL='https://lingering-math-d2ca.hansyow.workers.dev/'
        get_latest_release() {
          curl --silent "${PROXY_URL}https/api.github.com/repos/$1/releases/latest" | # Get latest release from GitHub api
            grep '"tag_name":' |                                            # Get tag line
            sed -E 's/.*"([^"]+)".*/\1/'                                    # Pluck JSON value
        }
        VERSION=$(get_latest_release $REPO)
        get_clash() {
                curl -L -s ${PROXY_URL}${GITHUB}/${USER}/${APP}/releases/download/${VERSION}/${APP}-${OS}-${VERSION}.gz -o ${FILE}
                gzip -d ${FILE}
                chmod 755 clash
        }
        get_clash
        mv clash VmessActions/clash && chmod 755 VmessActions/clash 
    - name: 部署规则转换服务
      run: |
        bash VmessActions/convert.sh
    - name: 爬取代理池
      run: |
        bash VmessActions/pool.sh
    - name: 提交更改
      run: |                 
         git config --local user.email "hansyow@gmail.com"
         git config --local user.name "hansyao"
         rm -rf subconverter
         git pull
         git add -f VmessActions/subscribe/
         if [[ $(git status | grep 'Changes to be committed') ]]; then git commit -m "更新订阅链接"; else echo '代理池没有变化'; fi
    - name: 推送更改
      uses:  ad-m/github-push-action@master
      with:
         branch: master
