name: 速度测试
on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: 迁出代码
      uses: actions/checkout@v2
     - name: 速度测试
      run: |
        bash VmessActions/proxy_rename_speedtest.sh
  
