<<<<<<< HEAD
name: 速度测速
=======
name: 速度测试
>>>>>>> bf2cc96 (update speedtest in workflows)
on:
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: 迁出代码
      uses: actions/checkout@v2
    - name: 设置时区
      run: sudo timedatectl set-timezone 'Asia/Shanghai'
     - name: 速度测试
      run: |
        bash VmessActions/proxy_rename_speedtest.sh
   - name: 推送更改
      uses:  ad-m/github-push-action@master
      with:
         branch: master
 
